- name: reboot
  command: shutdown -r +1 'Ansible Reboot triggered' && sleep 10
  async: 0
  poll: 0
  ignore_errors: true
  become: true

- name: wait for reboot to finish
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=50 timeout=120
  become: false